<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.9.1 on darwin)" generated="20210705 17:50:01.517" rpa="false">
<suite id="s1" name="Testcase" source="/Users/arunjohn/PycharmProjects/LearningProject/TestScripts/testcase.robot">
<test id="s1-t1" name="First Test case">
<status status="FAIL" starttime="20210705 17:50:02.041" endtime="20210705 17:50:02.042" critical="yes">Test case contains no keywords.</status>
</test>
<status status="FAIL" starttime="20210705 17:50:01.522" endtime="20210705 17:50:02.043"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Testcase">Testcase</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210705 17:50:01.509" level="ERROR">Error in file '/Users/arunjohn/PycharmProjects/LearningProject/TestScripts/testcase.robot' on line 4: Non-existing setting 'Resouce'. Did you mean:
    Resource</msg>
</errors>
</robot>
